# Generated by Django 4.1.2 on 2022-12-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("txnid", models.AutoField(primary_key=True, serialize=False)),
                ("uid", models.CharField(max_length=50)),
                ("amt", models.CharField(max_length=100)),
                ("info", models.CharField(max_length=100)),
            ],
        ),
    ]
