# Generated by Django 4.1.2 on 2022-11-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                ("regid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("email", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=15)),
                ("mobile", models.CharField(max_length=12)),
                ("address", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=20)),
                ("gender", models.CharField(max_length=10)),
                ("status", models.IntegerField()),
                ("role", models.CharField(max_length=10)),
                ("info", models.CharField(max_length=15)),
            ],
        ),
    ]
