# Generated by Django 4.1.2 on 2022-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mydjproject", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="info",
            field=models.CharField(max_length=50),
        ),
    ]
