# Generated by Django 4.1.2 on 2022-12-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("catid", models.AutoField(primary_key=True, serialize=False)),
                ("catname", models.CharField(max_length=50, unique=True)),
                ("caticonname", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                ("subcatid", models.AutoField(primary_key=True, serialize=False)),
                ("catname", models.CharField(max_length=50)),
                ("subcatname", models.CharField(max_length=50, unique=True)),
                ("subcaticonname", models.CharField(max_length=100)),
            ],
        ),
    ]
